import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useSelector } from 'react-redux';
import { useGetEmployeeDetailsQuery } from '../leaderboard/leaderboardApi';
export default function TargetsPage() {
    const { user, token } = useSelector((s) => s.auth);
    const employeeId = user?.employee_id;
    // Don't render anything if user is not authenticated
    if (!token || !employeeId) {
        return _jsx("div", { className: "p-4", children: "Please log in to view targets." });
    }
    const { data: employeeDetails, isLoading, error } = useGetEmployeeDetailsQuery(employeeId?.toString() || '', {
        skip: !employeeId
    });
    const formatCurrency = (amount) => {
        const numAmount = Number(amount) || 0;
        return `₹${numAmount.toLocaleString()}`;
    };
    const getProgressBarColor = (percentage) => {
        if (percentage >= 100)
            return 'bg-green-500';
        if (percentage >= 80)
            return 'bg-blue-500';
        if (percentage >= 60)
            return 'bg-yellow-500';
        return 'bg-red-500';
    };
    const renderMetricRow = (metric, type) => (_jsxs("tr", { className: "border-b border-gray-200", children: [_jsx("td", { className: "px-4 py-2 font-medium", children: metric.metric }), _jsx("td", { className: "px-4 py-2 text-center", children: metric.target.toLocaleString() }), _jsx("td", { className: "px-4 py-2 text-center font-semibold", children: metric.achievement.toLocaleString() }), _jsx("td", { className: "px-4 py-2", children: _jsxs("div", { className: "flex items-center space-x-2", children: [_jsx("div", { className: "flex-1 bg-gray-200 rounded-full h-2", children: _jsx("div", { className: `h-2 rounded-full ${getProgressBarColor(metric.achievement_percentage)}`, style: { width: `${Math.min(metric.achievement_percentage, 100)}%` } }) }), _jsxs("span", { className: "text-sm font-medium w-12", children: [metric.achievement_percentage.toFixed(1), "%"] })] }) }), _jsx("td", { className: "px-4 py-2 text-center font-semibold text-green-600", children: metric.earnings !== undefined && metric.earnings !== null
                    ? formatCurrency(metric.earnings)
                    : '₹0' })] }, `${type}-${metric.metric}`));
    if (!employeeId) {
        return (_jsx("div", { className: "min-h-screen bg-gray-50 flex items-center justify-center", children: _jsxs("div", { className: "text-center", children: [_jsx("p", { className: "text-lg text-gray-600 mb-2", children: "No employee information available" }), _jsx("p", { className: "text-sm text-gray-500", children: "Please ensure you are logged in with valid credentials" }), _jsxs("div", { className: "mt-4 p-4 bg-gray-100 rounded text-left text-xs", children: [_jsx("p", { children: _jsx("strong", { children: "Debug Info:" }) }), _jsxs("p", { children: ["User: ", JSON.stringify(user, null, 2)] }), _jsxs("p", { children: ["Employee ID: ", employeeId] }), _jsxs("p", { children: ["Token: ", token ? 'Present' : 'Missing'] })] })] }) }));
    }
    if (isLoading) {
        return (_jsx("div", { className: "min-h-screen bg-gray-50 flex items-center justify-center", children: _jsxs("div", { className: "text-center", children: [_jsx("div", { className: "animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500 mx-auto mb-4" }), _jsx("p", { className: "text-lg text-gray-600", children: "Loading your performance data..." })] }) }));
    }
    if (error) {
        return (_jsx("div", { className: "min-h-screen bg-gray-50 flex items-center justify-center", children: _jsxs("div", { className: "text-center", children: [_jsx("div", { className: "text-red-500 mb-4", children: _jsx("svg", { className: "w-16 h-16 mx-auto", fill: "currentColor", viewBox: "0 0 20 20", children: _jsx("path", { fillRule: "evenodd", d: "M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z", clipRule: "evenodd" }) }) }), _jsx("p", { className: "text-lg text-gray-600 mb-2", children: "Failed to load performance data" }), _jsx("p", { className: "text-sm text-gray-500", children: "Please try refreshing the page" }), _jsxs("div", { className: "mt-4 p-4 bg-red-50 rounded text-left text-xs", children: [_jsx("p", { children: _jsx("strong", { children: "Error Details:" }) }), _jsx("p", { children: JSON.stringify(error, null, 2) })] })] }) }));
    }
    if (!employeeDetails) {
        return (_jsx("div", { className: "min-h-screen bg-gray-50 flex items-center justify-center", children: _jsxs("div", { className: "text-center", children: [_jsx("div", { className: "text-gray-400 mb-4", children: _jsx("svg", { className: "w-16 h-16 mx-auto", fill: "currentColor", viewBox: "0 0 20 20", children: _jsx("path", { d: "M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" }) }) }), _jsx("p", { className: "text-lg text-gray-600 mb-2", children: "No performance data available" }), _jsx("p", { className: "text-sm text-gray-500", children: "Your performance metrics will appear here once data is available" })] }) }));
    }
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "bg-white rounded-lg shadow p-6", children: [_jsx("h1", { className: "text-2xl font-bold text-gray-900 mb-4", children: "My Performance Dashboard" }), _jsx("p", { className: "text-gray-600", children: "Detailed view of your targets vs achievements" }), employeeDetails && (_jsx("div", { className: "bg-blue-50 rounded-lg p-4 mt-4", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-lg font-semibold text-gray-900", children: employeeDetails.employee.name }), _jsxs("p", { className: "text-gray-600", children: ["Cluster: ", employeeDetails.employee.cluster, " \u2022 City: ", employeeDetails.employee.city] })] }), _jsxs("div", { className: "text-right", children: [_jsx("p", { className: "text-sm text-gray-600", children: "Employee ID" }), _jsx("p", { className: "text-lg font-bold text-blue-600", children: employeeDetails.employee.employee_id })] })] }) }))] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-2 gap-6", children: [_jsxs("div", { className: "bg-white rounded-lg shadow", children: [_jsx("div", { className: "p-6 border-b border-gray-200", children: _jsxs("h2", { className: "text-xl font-semibold text-gray-900", children: ["Daily Performance (", employeeDetails?.daily.date, ")"] }) }), employeeDetails?.daily?.metrics?.length > 0 ? (_jsx("div", { className: "p-6", children: _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { className: "bg-gray-50", children: _jsxs("tr", { children: [_jsx("th", { className: "px-4 py-2 text-left font-medium text-gray-700", children: "Metric" }), _jsx("th", { className: "px-4 py-2 text-center font-medium text-gray-700", children: "Target" }), _jsx("th", { className: "px-4 py-2 text-center font-medium text-gray-700", children: "Achieved" }), _jsx("th", { className: "px-4 py-2 text-center font-medium text-gray-700", children: "Progress" }), _jsx("th", { className: "px-4 py-2 text-center font-medium text-gray-700", children: "Earnings" })] }) }), _jsxs("tbody", { children: [employeeDetails.daily.metrics.map((metric) => renderMetricRow(metric, 'daily')), _jsxs("tr", { className: "bg-gray-50 font-semibold", children: [_jsx("td", { className: "px-4 py-3", children: "TOTAL" }), _jsx("td", { className: "px-4 py-3 text-center", children: employeeDetails.daily.totals.target.toLocaleString() }), _jsx("td", { className: "px-4 py-3 text-center", children: employeeDetails.daily.totals.achievement.toLocaleString() }), _jsx("td", { className: "px-4 py-3 text-center", children: employeeDetails.daily.totals.target > 0
                                                                    ? `${((employeeDetails.daily.totals.achievement / employeeDetails.daily.totals.target) * 100).toFixed(1)}%`
                                                                    : 'N/A' }), _jsx("td", { className: "px-4 py-3 text-center text-green-600", children: employeeDetails.daily.totals.earnings !== undefined && employeeDetails.daily.totals.earnings !== null
                                                                    ? formatCurrency(employeeDetails.daily.totals.earnings)
                                                                    : '₹0' })] })] })] }) }) })) : (_jsx("div", { className: "p-8 text-center text-gray-500", children: "No daily performance data available" }))] }), _jsxs("div", { className: "bg-white rounded-lg shadow", children: [_jsx("div", { className: "p-6 border-b border-gray-200", children: _jsx("h2", { className: "text-xl font-semibold text-gray-900", children: "Weekly Performance" }) }), employeeDetails?.weekly?.metrics?.length > 0 ? (_jsx("div", { className: "p-6", children: _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { className: "bg-gray-50", children: _jsxs("tr", { children: [_jsx("th", { className: "px-4 py-2 text-left font-medium text-gray-700", children: "Metric" }), _jsx("th", { className: "px-4 py-2 text-center font-medium text-gray-700", children: "Target" }), _jsx("th", { className: "px-4 py-2 text-center font-medium text-gray-700", children: "Achieved" }), _jsx("th", { className: "px-4 py-2 text-center font-medium text-gray-700", children: "Progress" }), _jsx("th", { className: "px-4 py-2 text-center font-medium text-gray-700", children: "Earnings" })] }) }), _jsxs("tbody", { children: [employeeDetails.weekly.metrics.map((metric) => renderMetricRow(metric, 'weekly')), _jsxs("tr", { className: "bg-gray-50 font-semibold", children: [_jsx("td", { className: "px-4 py-3", children: "TOTAL" }), _jsx("td", { className: "px-4 py-3 text-center", children: employeeDetails.weekly.totals.target.toLocaleString() }), _jsx("td", { className: "px-4 py-3 text-center", children: employeeDetails.weekly.totals.achievement.toLocaleString() }), _jsx("td", { className: "px-4 py-3 text-center", children: employeeDetails.weekly.totals.target > 0
                                                                    ? `${((employeeDetails.weekly.totals.achievement / employeeDetails.weekly.totals.target) * 100).toFixed(1)}%`
                                                                    : 'N/A' }), _jsx("td", { className: "px-4 py-3 text-center text-green-600", children: employeeDetails.weekly.totals.earnings !== undefined && employeeDetails.weekly.totals.earnings !== null
                                                                    ? formatCurrency(employeeDetails.weekly.totals.earnings)
                                                                    : '₹0' })] })] })] }) }) })) : (_jsx("div", { className: "p-8 text-center text-gray-500", children: "No weekly performance data available" }))] })] }), employeeDetails && (employeeDetails.daily.metrics.length > 0 || employeeDetails.weekly.metrics.length > 0) && (_jsxs("div", { className: "bg-white rounded-lg shadow p-6", children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-4", children: "Performance Summary" }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4", children: [_jsx("div", { className: "bg-green-50 rounded-lg p-4", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-green-800", children: "Daily Achievement" }), _jsx("p", { className: "text-2xl font-bold text-green-900", children: employeeDetails.daily.totals.achievement.toLocaleString() })] }), _jsx("div", { className: "text-green-500", children: _jsx("span", { className: "text-2xl", children: "\uD83D\uDCC8" }) })] }) }), _jsx("div", { className: "bg-blue-50 rounded-lg p-4", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-blue-800", children: "Weekly Achievement" }), _jsx("p", { className: "text-2xl font-bold text-blue-900", children: employeeDetails.weekly.totals.achievement.toLocaleString() })] }), _jsx("div", { className: "text-blue-500", children: _jsx("span", { className: "text-2xl", children: "\uD83D\uDCCA" }) })] }) }), _jsx("div", { className: "bg-yellow-50 rounded-lg p-4", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-yellow-800", children: "Daily Earnings" }), _jsx("p", { className: "text-2xl font-bold text-yellow-900", children: employeeDetails.daily.totals.earnings !== undefined && employeeDetails.daily.totals.earnings !== null
                                                        ? formatCurrency(employeeDetails.daily.totals.earnings)
                                                        : '₹0' })] }), _jsx("div", { className: "text-yellow-500", children: _jsx("span", { className: "text-2xl", children: "\uD83D\uDCB0" }) })] }) }), _jsx("div", { className: "bg-purple-50 rounded-lg p-4", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-purple-800", children: "Weekly Earnings" }), _jsx("p", { className: "text-2xl font-bold text-purple-900", children: employeeDetails.weekly.totals.earnings !== undefined && employeeDetails.weekly.totals.earnings !== null
                                                        ? formatCurrency(employeeDetails.weekly.totals.earnings)
                                                        : '₹0' })] }), _jsx("div", { className: "text-purple-500", children: _jsx("span", { className: "text-2xl", children: "\uD83D\uDC8E" }) })] }) })] })] }))] }));
}
