import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { useSelector } from 'react-redux';
import { useGetAssignedCustomersQuery, useGetInactiveCustomersQuery, useGetHighValueCustomersQuery } from './customersApi';
export default function CustomersPage() {
    const employeeId = useSelector((s) => s.auth.user?.employee_id || 0);
    const [tab, setTab] = useState('assigned');
    const assigned = useGetAssignedCustomersQuery(employeeId, { skip: !employeeId });
    const inactive = useGetInactiveCustomersQuery(employeeId, { skip: !employeeId });
    const high = useGetHighValueCustomersQuery(employeeId, { skip: !employeeId });
    const rows = tab === 'assigned' ? (assigned.data ?? []) : tab === 'inactive' ? (inactive.data ?? []) : (high.data ?? []);
    if (!employeeId)
        return _jsx("p", { className: "p-4", children: "No employee selected" });
    return (_jsx("div", { className: "min-h-screen bg-gray-50", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 py-6", children: [_jsxs("div", { className: "mb-6", children: [_jsx("h1", { className: "text-2xl font-bold text-gray-900 mb-2", children: "Customers" }), _jsx("p", { className: "text-gray-600", children: "Manage your customer relationships" })] }), _jsxs("div", { className: "flex gap-2 mb-6", children: [_jsxs("button", { onClick: () => setTab('assigned'), className: `px-4 py-2 rounded-lg font-medium transition-all ${tab === 'assigned'
                                ? 'bg-green-500 text-white shadow-sm'
                                : 'bg-white text-gray-700 border border-gray-200 hover:bg-gray-50'}`, children: ["Assigned (", assigned.data?.length || 0, ")"] }), _jsxs("button", { onClick: () => setTab('inactive'), className: `px-4 py-2 rounded-lg font-medium transition-all ${tab === 'inactive'
                                ? 'bg-green-500 text-white shadow-sm'
                                : 'bg-white text-gray-700 border border-gray-200 hover:bg-gray-50'}`, children: ["Inactive (", inactive.data?.length || 0, ")"] }), _jsxs("button", { onClick: () => setTab('high'), className: `px-4 py-2 rounded-lg font-medium transition-all ${tab === 'high'
                                ? 'bg-green-500 text-white shadow-sm'
                                : 'bg-white text-gray-700 border border-gray-200 hover:bg-gray-50'}`, children: ["High Value (", high.data?.length || 0, ")"] })] }), _jsx("div", { className: "bg-white rounded-xl shadow-sm border border-gray-200", children: rows.length > 0 ? (_jsx("div", { className: "divide-y divide-gray-200", children: rows.map((r) => (_jsx("div", { className: "p-4 hover:bg-gray-50 transition-colors", children: _jsxs("div", { className: "flex justify-between items-start", children: [_jsxs("div", { className: "flex-1", children: [_jsxs("div", { className: "flex items-center gap-3 mb-2", children: [_jsx("div", { className: "w-10 h-10 bg-indigo-100 rounded-full flex items-center justify-center", children: _jsx("span", { className: "text-sm font-semibold text-indigo-700", children: r.Customer ? r.Customer.toString().charAt(0).toUpperCase() : 'C' }) }), _jsxs("div", { children: [_jsx("h3", { className: "font-semibold text-gray-900", children: r.Customer ? r.Customer.toString() : r.name || 'Unknown Customer' }), _jsx("p", { className: "text-sm text-gray-500", children: r.City || 'Unknown City' })] })] }), _jsxs("div", { className: "ml-13 space-y-1", children: [_jsxs("p", { className: "text-sm text-gray-600", children: [_jsx("span", { className: "font-medium", children: "Segment:" }), " ", r.CustomerSegment || 'N/A'] }), _jsxs("p", { className: "text-sm text-gray-600", children: [_jsx("span", { className: "font-medium", children: "Type:" }), " ", r.CustomerType || 'N/A'] }), r.ContactNumber && (_jsxs("p", { className: "text-sm text-gray-600", children: [_jsx("span", { className: "font-medium", children: "Contact:" }), " ", r.ContactNumber] }))] })] }), _jsx("div", { className: "text-right", children: _jsx("div", { className: "bg-green-100 text-green-800 px-2 py-1 rounded-full text-xs font-semibold", children: r.Status || 'Active' }) })] }) }, r.CustomerId ?? r.Id))) })) : (_jsxs("div", { className: "text-center py-12", children: [_jsx("div", { className: "w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4", children: _jsx("span", { className: "text-2xl", children: "\uD83D\uDC65" }) }), _jsx("h3", { className: "text-lg font-medium text-gray-900 mb-2", children: "No customers found" }), _jsx("p", { className: "text-gray-500", children: "No customers match the selected filter" })] })) })] }) }));
}
