import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { useGetClusterLeaderboardQuery, useGetCityLeaderboardQuery, useGetUserProfileQuery, useGetEmployeeDetailsQuery } from './leaderboardApi';
import { useSelector } from 'react-redux';
export default function LeaderBoardPage() {
    const [activeTab, setActiveTab] = useState('cluster');
    const [selectedEmployee, setSelectedEmployee] = useState(null);
    const { user, token } = useSelector((s) => s.auth);
    const employeeId = user?.employee_id;
    // Don't render anything if user is not authenticated
    if (!token || !employeeId) {
        return _jsx("div", { className: "p-4", children: "Please log in to view the leaderboard." });
    }
    const { data: userProfile } = useGetUserProfileQuery(employeeId, { skip: !employeeId });
    const { data: clusterData } = useGetClusterLeaderboardQuery(userProfile?.cluster || '', { skip: !userProfile?.cluster });
    const { data: cityData } = useGetCityLeaderboardQuery(Number(userProfile?.CityId) || 0, { skip: !userProfile?.CityId });
    const { data: employeeDetails } = useGetEmployeeDetailsQuery(selectedEmployee || '', {
        skip: !selectedEmployee
    });
    const leaderboardData = activeTab === 'cluster' ? clusterData : cityData;
    const formatCurrency = (amount) => {
        const numAmount = Number(amount) || 0;
        return `₹${numAmount.toLocaleString()}`;
    };
    const getProgressBarColor = (percentage) => {
        if (percentage >= 100)
            return 'bg-green-500';
        if (percentage >= 80)
            return 'bg-blue-500';
        if (percentage >= 60)
            return 'bg-yellow-500';
        return 'bg-red-500';
    };
    const renderMetricRow = (metric, type) => (_jsxs("tr", { className: "border-b border-gray-200", children: [_jsx("td", { className: "px-4 py-2 font-medium", children: metric.metric }), _jsx("td", { className: "px-4 py-2 text-center", children: metric.target.toLocaleString() }), _jsx("td", { className: "px-4 py-2 text-center font-semibold", children: metric.achievement.toLocaleString() }), _jsx("td", { className: "px-4 py-2", children: _jsxs("div", { className: "flex items-center space-x-2", children: [_jsx("div", { className: "flex-1 bg-gray-200 rounded-full h-2", children: _jsx("div", { className: `h-2 rounded-full ${getProgressBarColor(metric.achievement_percentage)}`, style: { width: `${Math.min(metric.achievement_percentage, 100)}%` } }) }), _jsxs("span", { className: "text-sm font-medium w-12", children: [metric.achievement_percentage.toFixed(1), "%"] })] }) }), _jsx("td", { className: "px-4 py-2 text-center font-semibold text-green-600", children: metric.earnings !== undefined && metric.earnings !== null ? formatCurrency(metric.earnings) : '₹0' })] }, `${type}-${metric.metric}`));
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "bg-white rounded-lg shadow p-6", children: [_jsx("h1", { className: "text-2xl font-bold text-gray-900 mb-4", children: "Leaderboard" }), userProfile && (_jsx("div", { className: "bg-blue-50 rounded-lg p-4 mb-4", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-lg font-semibold text-gray-900", children: userProfile.name }), _jsxs("p", { className: "text-gray-600", children: ["Cluster: ", userProfile.cluster, " \u2022 City: ", userProfile.city] })] }), _jsxs("div", { className: "text-right", children: [_jsx("p", { className: "text-sm text-gray-600", children: "Your Rankings" }), _jsxs("p", { className: "text-lg font-bold text-blue-600", children: ["#", userProfile.cluster_rank, " in Cluster \u2022 #", userProfile.city_rank, " in City"] })] })] }) })), _jsxs("div", { className: "flex space-x-1 mb-6", children: [_jsxs("button", { onClick: () => setActiveTab('cluster'), className: `px-4 py-2 rounded-lg font-medium ${activeTab === 'cluster'
                                    ? 'bg-blue-600 text-white'
                                    : 'bg-gray-200 text-gray-700 hover:bg-gray-300'}`, children: ["Cluster Leaderboard (", userProfile?.cluster, ")"] }), _jsxs("button", { onClick: () => setActiveTab('city'), className: `px-4 py-2 rounded-lg font-medium ${activeTab === 'city'
                                    ? 'bg-blue-600 text-white'
                                    : 'bg-gray-200 text-gray-700 hover:bg-gray-300'}`, children: ["City Leaderboard (", userProfile?.city, ")"] })] })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-2 gap-6", children: [_jsxs("div", { className: "bg-white rounded-lg shadow", children: [_jsx("div", { className: "p-6 border-b border-gray-200", children: _jsx("h2", { className: "text-xl font-semibold text-gray-900", children: activeTab === 'cluster' ? 'Cluster Rankings' : 'City Rankings' }) }), _jsx("div", { className: "max-h-96 overflow-y-auto", children: leaderboardData?.length > 0 ? (_jsx("div", { className: "divide-y divide-gray-200", children: leaderboardData.map((employee, index) => (_jsx("div", { className: `p-4 cursor-pointer hover:bg-gray-50 transition-colors ${employee.employee_id?.toString() === employeeId?.toString() ? 'bg-blue-50 border-l-4 border-blue-500' : ''}`, onClick: () => setSelectedEmployee(employee.employee_id), children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center space-x-3", children: [_jsxs("div", { className: `w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold ${index === 0 ? 'bg-yellow-500 text-white' :
                                                                index === 1 ? 'bg-gray-400 text-white' :
                                                                    index === 2 ? 'bg-orange-500 text-white' :
                                                                        'bg-gray-200 text-gray-700'}`, children: ["#", employee.rank] }), _jsxs("div", { children: [_jsx("p", { className: "font-medium text-gray-900", children: employee.Name || `Employee ${employee.employee_id}` }), _jsx("p", { className: "text-sm text-gray-600", children: activeTab === 'cluster' ? employee.cluster : employee.city_name })] })] }), _jsxs("div", { className: "text-right", children: [_jsx("p", { className: "font-semibold text-blue-600", children: employee.weekly_achievements !== undefined && employee.weekly_achievements !== null
                                                                ? employee.weekly_achievements.toLocaleString()
                                                                : '0' }), _jsx("p", { className: "text-xs text-gray-500", children: "Weekly Units" })] })] }) }, employee.employee_id || index))) })) : (_jsx("div", { className: "p-8 text-center text-gray-500", children: "No leaderboard data available" })) })] }), _jsx("div", { className: "bg-white rounded-lg shadow", children: selectedEmployee ? (_jsxs(_Fragment, { children: [_jsx("div", { className: "p-6 border-b border-gray-200", children: _jsx("h2", { className: "text-xl font-semibold text-gray-900", children: "Employee Details" }) }), employeeDetails ? (_jsxs("div", { className: "p-6 space-y-6", children: [_jsxs("div", { className: "bg-gray-50 rounded-lg p-4", children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-2", children: employeeDetails.employee.name }), _jsxs("div", { className: "grid grid-cols-2 gap-4 text-sm", children: [_jsxs("div", { children: [_jsx("span", { className: "font-medium text-gray-600", children: "Employee ID:" }), _jsx("span", { className: "ml-2", children: employeeDetails.employee.employee_id })] }), _jsxs("div", { children: [_jsx("span", { className: "font-medium text-gray-600", children: "Cluster:" }), _jsx("span", { className: "ml-2", children: employeeDetails.employee.cluster })] }), _jsxs("div", { children: [_jsx("span", { className: "font-medium text-gray-600", children: "City:" }), _jsx("span", { className: "ml-2", children: employeeDetails.employee.city })] })] })] }), _jsxs("div", { children: [_jsxs("h4", { className: "text-lg font-semibold text-gray-900 mb-3", children: ["Daily Performance (", employeeDetails.daily.date, ")"] }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { className: "bg-gray-50", children: _jsxs("tr", { children: [_jsx("th", { className: "px-4 py-2 text-left font-medium text-gray-700", children: "Metric" }), _jsx("th", { className: "px-4 py-2 text-center font-medium text-gray-700", children: "Target" }), _jsx("th", { className: "px-4 py-2 text-center font-medium text-gray-700", children: "Achieved" }), _jsx("th", { className: "px-4 py-2 text-center font-medium text-gray-700", children: "Progress" }), _jsx("th", { className: "px-4 py-2 text-center font-medium text-gray-700", children: "Earnings" })] }) }), _jsxs("tbody", { children: [employeeDetails.daily.metrics.map((metric) => renderMetricRow(metric, 'daily')), _jsxs("tr", { className: "bg-gray-50 font-semibold", children: [_jsx("td", { className: "px-4 py-3", children: "TOTAL" }), _jsx("td", { className: "px-4 py-3 text-center", children: employeeDetails.daily.totals.target.toLocaleString() }), _jsx("td", { className: "px-4 py-3 text-center", children: employeeDetails.daily.totals.achievement.toLocaleString() }), _jsx("td", { className: "px-4 py-3 text-center", children: employeeDetails.daily.totals.target > 0
                                                                                    ? `${((employeeDetails.daily.totals.achievement / employeeDetails.daily.totals.target) * 100).toFixed(1)}%`
                                                                                    : 'N/A' }), _jsx("td", { className: "px-4 py-3 text-center text-green-600", children: employeeDetails.daily.totals.earnings !== undefined && employeeDetails.daily.totals.earnings !== null
                                                                                    ? formatCurrency(employeeDetails.daily.totals.earnings)
                                                                                    : '₹0' })] })] })] }) })] }), _jsxs("div", { children: [_jsx("h4", { className: "text-lg font-semibold text-gray-900 mb-3", children: "Weekly Performance" }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { className: "bg-gray-50", children: _jsxs("tr", { children: [_jsx("th", { className: "px-4 py-2 text-left font-medium text-gray-700", children: "Metric" }), _jsx("th", { className: "px-4 py-2 text-center font-medium text-gray-700", children: "Target" }), _jsx("th", { className: "px-4 py-2 text-center font-medium text-gray-700", children: "Achieved" }), _jsx("th", { className: "px-4 py-2 text-center font-medium text-gray-700", children: "Progress" }), _jsx("th", { className: "px-4 py-2 text-center font-medium text-gray-700", children: "Earnings" })] }) }), _jsxs("tbody", { children: [employeeDetails.weekly.metrics.map((metric) => renderMetricRow(metric, 'weekly')), _jsxs("tr", { className: "bg-gray-50 font-semibold", children: [_jsx("td", { className: "px-4 py-3", children: "TOTAL" }), _jsx("td", { className: "px-4 py-3 text-center", children: employeeDetails.weekly.totals.target.toLocaleString() }), _jsx("td", { className: "px-4 py-3 text-center", children: employeeDetails.weekly.totals.achievement.toLocaleString() }), _jsx("td", { className: "px-4 py-3 text-center", children: employeeDetails.weekly.totals.target > 0
                                                                                    ? `${((employeeDetails.weekly.totals.achievement / employeeDetails.weekly.totals.target) * 100).toFixed(1)}%`
                                                                                    : 'N/A' }), _jsx("td", { className: "px-4 py-3 text-center text-green-600", children: employeeDetails.weekly.totals.earnings !== undefined && employeeDetails.weekly.totals.earnings !== null
                                                                                    ? formatCurrency(employeeDetails.weekly.totals.earnings)
                                                                                    : '₹0' })] })] })] }) })] })] })) : (_jsx("div", { className: "p-8 text-center text-gray-500", children: "Loading employee details..." }))] })) : (_jsx("div", { className: "p-8 text-center text-gray-500", children: "Click on an employee to view detailed performance metrics" })) })] })] }));
}
