import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useTheme } from '../../shared/ThemeContext';
import { ThemedCard, ThemedBadge, ThemedProgress } from '../../shared';
export default function ThemeTestPage() {
    const { currentTheme, toggleTheme } = useTheme();
    return (_jsx("div", { className: "min-h-screen bg-gray-50 dark:bg-gray-900 p-8", children: _jsxs("div", { className: "max-w-4xl mx-auto", children: [_jsxs("div", { className: "mb-8", children: [_jsx("h1", { className: "text-3xl font-bold text-gray-900 dark:text-white mb-4", children: "Theme System Test" }), _jsxs("div", { className: "flex items-center gap-4", children: [_jsxs("button", { onClick: toggleTheme, className: "px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors", children: ["Toggle Theme (Current: ", currentTheme.name, ")"] }), _jsxs("div", { className: "text-sm text-gray-600 dark:text-gray-400", children: ["isDark: ", currentTheme.isDark.toString(), ", isNeon: ", currentTheme.isNeon.toString()] })] })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsxs(ThemedCard, { accent: "amber", children: [_jsxs("div", { className: "flex items-center justify-between mb-3", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: `w-14 h-14 rounded-2xl flex items-center justify-center ${currentTheme.isDark
                                                        ? 'bg-white/5 ring-1 ring-white/10'
                                                        : 'bg-gradient-to-br from-amber-400 to-orange-500 shadow-lg shadow-amber-300/30'}`, children: _jsx("span", { className: "text-3xl", children: "\uD83D\uDCB0" }) }), _jsxs("div", { children: [_jsx("h3", { className: `text-xl font-bold ${currentTheme.isDark ? 'text-[var(--text)]' : 'text-gray-900'}`, children: "Daily Target" }), _jsx("p", { className: `text-sm font-bold ${currentTheme.isDark ? 'text-yellow-200/90' : 'text-amber-900'}`, children: "Pending to earn" })] })] }), _jsx(ThemedBadge, { children: "RANK 1" })] }), _jsxs("div", { children: [_jsx("p", { className: `text-5xl font-extrabold mb-3 ${currentTheme.isDark ? 'text-cyan-300' : 'text-gray-900'}`, children: "\u20B91,500" }), _jsxs("div", { className: "flex justify-between text-sm mb-3", children: [_jsx("span", { className: `font-bold ${currentTheme.isDark ? 'text-yellow-200' : 'text-amber-900'}`, children: "Progress" }), _jsx("span", { className: `font-bold ${currentTheme.isDark ? 'text-[var(--text)]' : 'text-gray-900'}`, children: "75% complete" })] }), _jsx(ThemedProgress, { value: 75, theme: "amber" })] })] }), _jsxs(ThemedCard, { accent: "purple", children: [_jsxs("div", { className: "flex items-center justify-between mb-3", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: `w-14 h-14 rounded-2xl flex items-center justify-center ${currentTheme.isDark
                                                        ? 'bg-white/5 ring-1 ring-white/10'
                                                        : 'bg-gradient-to-br from-pink-500 to-red-500 shadow-lg shadow-pink-300/30'}`, children: _jsx("span", { className: "text-3xl", children: "\uD83D\uDCC5" }) }), _jsxs("div", { children: [_jsx("h3", { className: `text-xl font-bold ${currentTheme.isDark ? 'text-[var(--text)]' : 'text-gray-900'}`, children: "Weekly Target" }), _jsx("p", { className: `text-sm font-bold ${currentTheme.isDark ? 'text-purple-200/90' : 'text-green-800'}`, children: "Keep your streak alive" })] })] }), _jsx(ThemedBadge, { children: "5 DAY STREAK" })] }), _jsxs("div", { children: [_jsx("p", { className: `text-5xl font-extrabold mb-3 ${currentTheme.isDark ? 'text-cyan-300' : 'text-gray-900'}`, children: "\u20B98,500" }), _jsxs("div", { className: "flex justify-between text-sm mb-3", children: [_jsx("span", { className: `font-bold ${currentTheme.isDark ? 'text-purple-200' : 'text-rose-800'}`, children: "Progress" }), _jsx("span", { className: `font-bold ${currentTheme.isDark ? 'text-[var(--text)]' : 'text-gray-900'}`, children: "60% complete" })] }), _jsx(ThemedProgress, { value: 60, theme: "rose" })] })] })] }), _jsxs("div", { className: "mt-8 bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-lg", children: [_jsx("h2", { className: "text-xl font-bold text-gray-900 dark:text-white mb-4", children: "Current Theme Configuration" }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4 text-sm", children: [_jsxs("div", { children: [_jsx("h3", { className: "font-semibold text-gray-700 dark:text-gray-300 mb-2", children: "Theme Properties:" }), _jsxs("ul", { className: "space-y-1 text-gray-600 dark:text-gray-400", children: [_jsxs("li", { children: ["Name: ", currentTheme.name] }), _jsxs("li", { children: ["Is Dark: ", currentTheme.isDark.toString()] }), _jsxs("li", { children: ["Is Neon: ", currentTheme.isNeon.toString()] })] })] }), _jsxs("div", { children: [_jsx("h3", { className: "font-semibold text-gray-700 dark:text-gray-300 mb-2", children: "Colors:" }), _jsxs("ul", { className: "space-y-1 text-gray-600 dark:text-gray-400", children: [_jsxs("li", { children: ["Primary: ", currentTheme.colors.primary] }), _jsxs("li", { children: ["Secondary: ", currentTheme.colors.secondary] }), _jsxs("li", { children: ["Background: ", currentTheme.colors.background] }), _jsxs("li", { children: ["Text: ", currentTheme.colors.text] })] })] })] })] })] }) }));
}
